# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseherramienta',
            name='imagen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studley.Imagen'),
        ),
    ]
