# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0014_auto_20151224_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='logo',
        ),
    ]
