# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0016_tipoherramienta_nombre_plural'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoherramienta',
            name='nombre_plural',
        ),
    ]
