# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0017_remove_tipoherramienta_nombre_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoherramienta',
            name='nombre_plural',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
