# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0020_tipoherramienta_nombre_corto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoherramienta',
            name='nombre_corto',
            field=models.SlugField(help_text='Debe ser único.', max_length=30, unique=True),
        ),
    ]
