# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0023_auto_20151226_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coleccion',
            old_name='notas',
            new_name='descripcion',
        ),
    ]
