# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0024_auto_20151226_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claseherramienta',
            name='imagen',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='studley.Imagen'),
        ),
        migrations.AlterField(
            model_name='herramientabase',
            name='tipo',
            field=models.ForeignKey(blank=True, help_text='Tipo o nombre genérico. E.g. Serrucho, el cual es el tipo de ´de corte fino´, ´de costilla´, etc.', on_delete=django.db.models.deletion.CASCADE, to='studley.TipoHerramienta'),
        ),
    ]
