# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studley', '0026_auto_20160109_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramientabase',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
