# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0028_auto_20160110_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseherramienta',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coleccion',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herramientabase',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marca',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipoherramienta',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
