# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 03:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0029_auto_20160111_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseherramienta',
            name='fecha_actualizacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='claseherramienta',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
