# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import studley.models


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0030_auto_20160111_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to=studley.models.change_uploaded_filename),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(blank=True, default='imagen', max_length=150),
        ),
    ]
