# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studley', '0031_auto_20160226_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoherramienta',
            options={'verbose_name': 'Tipo herramienta', 'verbose_name_plural': 'Tipos herramientas'},
        ),
    ]
