# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 01:11
from __future__ import unicode_literals

import cueva.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestacadoHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenFondoHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=cueva.models.change_uploaded_filename)),
                ('nombre', models.CharField(default='sin título', max_length=150)),
                ('autor', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField(blank=True)),
                ('licencia', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Imagen inicio',
                'verbose_name_plural': 'Imágenes inicio',
            },
        ),
    ]
