# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 02:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maloof', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 1, 22, 2, 37, 31, 752338, tzinfo=utc)),
        ),
    ]
