# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 03:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maloof', '0003_auto_20160121_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 1, 22, 3, 26, 17, 864232, tzinfo=utc)),
        ),
    ]
