# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maloof', '0007_auto_20160127_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 1, 27, 16, 30, 37, 384418, tzinfo=utc)),
        ),
    ]
