# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maloof', '0008_auto_20160127_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('CLI', 'Cliente'), ('ART', 'Artesano'), ('SOC', 'Socio'), ('ADM', 'Administrador')], default='CLI', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 2, 5, 23, 29, 32, 548262, tzinfo=utc)),
        ),
    ]
