# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 23:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maloof', '0009_auto_20160205_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 2, 26, 23, 31, 59, 296344, tzinfo=utc)),
        ),
    ]
