# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 01:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('maloof', '0011_auto_20160226_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 2, 27, 1, 16, 24, 872575, tzinfo=utc)),
        ),
    ]
