# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ojo con la ortografía de los títulos en español. Máximo 150 caracteres.', max_length=150)),
                ('nombre_corto', models.SlugField(help_text='Nombre corto que se usa para la URL: letras, números, guiones, rayas). Debe ser único.')),
                ('cuerpo', models.TextField(help_text='Descripción o instrucciones del recurso si es un adjunto o URL; contenido completo si es un texto o multimedia para deplegar en línea en la lección. Puede ser HTML.')),
                ('tipo', models.CharField(choices=[('BLG', 'Blog'), ('GLR', 'Galería'), ('PRY', 'Proyecto'), ('TUT', 'Tutorial'), ('VID', 'Video'), ('DOC', 'Doc')], max_length=5)),
                ('url', models.URLField(blank=True, help_text='URL del recurso si proviene de otro sitio, como Youtube, Slideshare, o si también fue publicado en otro lugar.')),
                ('imagen_destacada', models.ImageField(blank=True, help_text='Imagen que se verá en los destacados y listas del recurso.', upload_to='recursos')),
            ],
            options={
                'verbose_name_plural': 'Recursos',
                'ordering': ['nombre_corto'],
            },
        ),
        migrations.CreateModel(
            name='RecursosAutores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roubo.Recurso', verbose_name='Recurso')),
            ],
            options={
                'verbose_name_plural': 'Autores y recursos',
                'verbose_name': 'Autores y recursos',
            },
        ),
        migrations.AddField(
            model_name='recurso',
            name='autor',
            field=models.ManyToManyField(through='roubo.RecursosAutores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Lista de tags separados por comas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
