# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roubo', '0003_auto_20151230_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destacado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticky', models.BooleanField(default=False)),
                ('orden', models.IntegerField()),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roubo.Recurso')),
            ],
            options={
                'verbose_name_plural': 'Destacados',
            },
        ),
    ]
