# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubo', '0006_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default='exautor@emailserver.com', max_length=254),
            preserve_default=False,
        ),
    ]
