# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubo', '0007_contacto_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='autor',
            field=models.CharField(max_length=50),
        ),
    ]
