# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 00:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubo', '0008_auto_20160104_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='acepto_contacto',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='acepto_tratamiento',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
