# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roubo', '0009_auto_20160105_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='cuerpo',
            field=models.TextField(help_text='Descripción o instrucciones del recurso si es un adjunto                   o URL; contenido completo si es un texto o multimedia para                   deplegar en línea en la lección. Puede ser HTML.'),
        ),
    ]
